[package]
name = "httun-httpserver"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true
categories.workspace = true
keywords.workspace = true
publish = false

[dependencies]
anyhow = { workspace = true }
atoi = { workspace = true }
base64 = { workspace = true }
clap = { workspace = true }
console-subscriber = { workspace = true }
env_logger = { workspace = true }
httun-conf = { workspace = true }
httun-protocol = { workspace = true }
httun-unix-protocol = { workspace = true }
httun-util = { workspace = true }
log = { workspace = true }
memchr = { workspace = true }
nix = { workspace = true }
tokio = { workspace = true, features = [ "rt-multi-thread", "signal", "sync", "net", "time", "macros", "tracing", "io-util" ] }

[lints]
workspace = true
